POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Cu3"
}

###

GET http://localhost:3333/courses 

###

GET http://localhost:3333/courses/f0272cb8-8e3e-42fb-a7f9-d6c907fb7867


###

DELETE http://localhost:3333/courses/baebc28d-4708-4677-9a48-3b8605408841