POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker"
}

###

GET http://localhost:3333/courses 

###

GET http://localhost:3333/courses/bd714ae2-390a-4db9-940f-50169c752683
