POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker"
}

###

GET http://localhost:3333/courses 

###

GET http://localhost:3333/courses/3


###

DELETE http://localhost:3333/courses/baebc28d-4708-4677-9a48-3b8605408841